# Generated by Django 5.2.3 on 2025-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('skills', models.TextField(help_text='Skills separated by comma')),
                ('projects', models.TextField(help_text='Projects separated by comma')),
                ('bio', models.TextField(blank=True)),
                ('contacts', models.JSONField(default=dict, help_text="Contact information as a dict. Example: {'phone': '+38099...', 'email': 'help@dteam.dev'}")),
            ],
        ),
    ]
